# -------------
# Site settings
# -------------

title: hTools3 user documentation
email: gustavo@hipertipo.com
description: hTools3 user documentation
baseurl: ""
url: https://hipertipo.gitlab.io/htools3_core_extension/
twitter_username: jekyllrb
github_username:  jekyll

collections:
  batch:
    output: true
    permalink: /:collection/:path/
  font:
    output: true
    permalink: /:collection/:path/
  glyph:
    output: true
    permalink: /:collection/:path/
  glyphs:
    output: true
    permalink: /:collection/:path/

# --------------
# Build settings
# --------------

markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
